- name: Retrieve secret from Azure Key Vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    name: "{{ secret_name }}"
    vault_uri: "https://{{ key_vault_name }}.vault.azure.net/"
    subscription_id: "cc323661-bdfb-4e37-8224-b9f41308d182"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tenant: "{{ azure_tenant_id }}"
  register: secret_result

- name: Base64 encode the secret
  set_fact:
    encoded_secret_value: "{{ secret_result.secrets[0].value | b64encode }}"

- name: Create Kubernetes secret
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ kubernetes_secret_name }}"
        namespace: "{{ kubernetes_namespace }}"
      type: Opaque
      data:
        password: "{{ encoded_secret_value }}"